version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_test_integration
    ports:
      - "5433:5432"  # Porta diferente para o banco de dados de teste
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  postgres_test_data: